# Generated by Django 5.2.16 on 2026-08-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="position",
            field=models.CharField(
                blank=True,
                choices=[("secondary", "Secondary"), ("main", "Main")],
                max_length=20,
                null=True,
            ),
        ),
    ]
