# Generated by Django 6.1 on 2026-08-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_grade_created_by_alter_grade_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='grade_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
