# Generated by Django 6.0.5 on 2026-08-07 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('masking', 'Основи маскування'), ('planning', 'Планування операцій'), ('teamwork', 'Командна робота'), ('security', 'Обхід систем безпеки'), ('codes', 'Шифри та коди')], max_length=20)),
                ('material_type', models.CharField(choices=[('file', 'Файл'), ('image', 'Зображення'), ('link', 'Посилання'), ('youtube', 'YouTube')], default='file', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
