# Generated by Django 5.2.16 on 2026-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="material_type",
            field=models.CharField(
                choices=[
                    ("file", "Файл"),
                    ("image", "Зображення"),
                    ("link", "Посилання"),
                    ("youtube", "YouTube"),
                ],
                default="file",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="material",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, blank=True, max_length=255, unique=True
            ),
        ),
    ]
