# Generated by Django 5.2.16 on 2026-08-27 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_material_type_material_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок відображення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
            ],
            options={
                'verbose_name': 'Категорія матеріалів',
                'verbose_name_plural': 'Категорії матеріалів',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['-created_at'], 'verbose_name': 'Навчальний матеріал', 'verbose_name_plural': 'Навчальні матеріали'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='link',
        ),
        migrations.AddField(
            model_name='material',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Зовнішнє посилання'),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='materials/images/', verbose_name='Зображення'),
        ),
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AddField(
            model_name='material',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube-посилання'),
        ),
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='material',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Опис матеріалу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='material',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AlterField(
            model_name='material',
            name='material_type',
            field=models.CharField(choices=[('file', 'Файл'), ('image', 'Зображення'), ('link', 'Зовнішнє посилання'), ('youtube', 'YouTube-відео')], max_length=20, verbose_name='Тип матеріалу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Slug (URL)'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва матеріалу'),
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='materials.materialcategory', verbose_name='Категорія'),
        ),
    ]
